language: php
php:
  - 5.5
branches:
  only:
    - master
    - develop
before_script:
  - curl -s http://getcomposer.org/installer | php
  - printf "\n" | pecl install memcached
  - echo "extension=memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
#  - composer install -n --dev
  - php composer.phar install --dev --no-interaction
#  - php composer.phar install --dev
#  - php vendor/bin/coveralls -v
script:
  - mkdir -p build/logs
  - phpunit -c app

after_script:
  - php vendor/satooshi/php-coveralls/composer/bin/coveralls -v

notifications:
  email:
    - hkamei06@gmail.com
  on_success: always # default: change
  on_failure: always